### ISSUE TITLE
Increase precision of sensor readouts

### ISSUE THREAD

**Issue by dazza5000** [BruceGiese/misc#3]
From the physical therapist persona:

Can the numbers be changed to get more accuracy?  Or changed to degrees?  I think this will allow us to give better feedback to the user.

**Comment by BruceGiese** [comment]
I set the precision to be controlled by the parameter MAX_INTEGER in Orientation.java.  Right now it's set to 10.  If I set it to 180, that should result in something close to degrees.  The real limiting factor might be the actual accuracy of the sensors.

One thing I was thinking about was using a running average of the angle so that we don't send a notification unless they've been holding it at that angle for more than a certain amount of time; say 10 seconds.

**Comment by dazza5000** [comment]
Agreed. A moving average and some allowance for a range would be more user friendly :)

**Comment by BruceGiese** [comment]
I've increased this to plus or minus 180 degrees, although it can be slightly off.

**Comment by dazza5000** [comment]
:100:
